name: artifactory

on:
    push:
        branches:
            - main
jobs:
    uploadartifacts:
        name: upload artifactiry
        runs-on: ubuntu-latest
        steps:
            - name: create a directory
              run: mkdir artifactory
            - name: create a file
              run: touch artifactory/art.txt
            - name: write content 
              run: echo "hello, learning artifactory" >artifactory/art.txtart.txt
            - name: upload the artifcatory
              uses: actions/upload-artifact@v4
              with:
                name: artifcats
                path: artifactory/art.txt
    downloadartifcats:
        name: download artficat
        runs-on: ubuntu-lates
        steps:
            - name: download the artifcat
              uses: actions/download-artifact@v4
              with:
                name: artifacts
            - name: dispaly contents
              run: cat artifcats/art.txt

