name: artifactory

on:
    push:
        branches:
            - main
jobs:
    uploadartifacts:
        name: upload artifactiry
        runs-on: ubuntu-latest
        steps:
            - name: create a directory
              run: mkdir artifactory
            - name: create a file
              run: touch artifactory/art.txt
            - name: write content 
              run: echo "hello, learning artifsctory" >>art.txt
            - name: upload the artifcatory
              uses: actions/upload-artifact@v4
              with:
                name: artifcats
                path: artifactory1/art.txt
        
